project:
  type: book
  output-dir: docs

execute:
  echo: true
  message: false
  warning: false

book:
  title: "Economic Growth and the Shrinking Family: A Cross-Country Exploration"
  author:
    - Jan Barganowski (jgb2170)
    - Matt Pisinski (mp4523)
  repo-url: https://github.com/jan-barg/EDAV-Final-Jan-Matt.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: litera
    code-fold: true


